### ISSUE TITLE
类Student继承Person类后，Student的构造函数内部应该先调用super(name);否则编译器报错。

### ISSUE THREAD

**Issue by BetterZhang** [githubhaohao/JavaToKotlin#1]
public final class Student extends Person {

    private String school = null;

    public Student(String name, String school) {
        super(name);
        this.school = school;
    }

    @override
    public void sayHello() {
        super.sayHello();
        System.out.println("Hello Student");
    }

}

**Comment by githubhaohao** [comment]
谢谢纠正，已修改。
